-- ENABLE GEODATABASE REQUIRED SDE USER PERMISSIONS

GRANT ADMINISTER DATABASE TRIGGER TO SDE;
GRANT ADMINISTER DATABASE TRIGGER TO SDE;
GRANT ALTER ANY INDEX TO SDE;
GRANT ALTER SESSION TO SDE;
GRANT ALTER SYSTEM TO SDE;
GRANT ANALYZE ANY TO SDE;
GRANT CREATE ANY INDEX  TO SDE;
GRANT CREATE ANY TRIGGER TO SDE;
GRANT CREATE ANY VIEW TO SDE;
GRANT CREATE DATABASE LINK TO SDE;
GRANT CREATE INDEXTYPE TO SDE;
GRANT CREATE LIBRARY  TO SDE;
GRANT CREATE MATERIALIZED VIEW TO SDE;
GRANT CREATE OPERATOR TO SDE;
GRANT CREATE PROCEDURE TO SDE;
GRANT CREATE PUBLIC SYNONYM TO SDE;
GRANT CREATE SEQUENCE TO SDE;
GRANT CREATE SESSION TO SDE;
GRANT CREATE TABLE TO SDE;
GRANT CREATE TRIGGER TO SDE;
GRANT CREATE TYPE TO SDE;
GRANT CREATE VIEW TO SDE;
GRANT DROP ANY INDEX TO SDE;
GRANT DROP ANY VIEW TO SDE;
GRANT DROP PUBLIC SYNONYM TO SDE;
GRANT EXECUTE ON DBMS_CRYPTO TO SDE;
GRANT EXECUTE ON dbms_lob TO public;
GRANT EXECUTE ON dbms_lock TO public;
GRANT EXECUTE ON dbms_pipe TO public;
GRANT EXECUTE ON dbms_sql TO public;
GRANT EXECUTE ON dbms_utility TO public;
GRANT EXECUTE ON utl_raw TO public;
GRANT RESTRICTED SESSION TO SDE;
GRANT SELECT ANY DICTIONARY TO SDE;
GRANT SELECT ANY TABLE TO SDE;
GRANT SELECT ON DBA_ROLES TO SDE;
GRANT SELECT_CATALOG_ROLE  TO SDE;
GRANT UNLIMITED TABLESPACE  TO SDE;

-- POST INSTALL - REMOVE SYSTEM TABLES FROM VIEW
-- ArcGIS Pro requires removal of only SELECT ANY TABLE
-- ArcMAP may require the other selects or specific blocks to show only GIS Data tables.

--REVOKE SELECT ANY TABLE FROM SDE;
--REVOKE SELECT ANY DICTIONARY FROM SDE;
--REVOKE SELECT_CATALOG_ROLE FROM SDE;
